### ISSUE TITLE
Research SOLID

### ISSUE THREAD

**Issue by SieBRUM** [ACI-Rental/backend#44]
Currently all controllers contain business logic (like checks etc). This might go against the Controller rules.

Research (and build) if it's useful to implement something like a 'Unit of Work' or some other layer so the logic inside controllers is minimized.

**Comment by KrzysztofBorowiecki** [comment]
Hi I started doing this Issue but I have question. I move DbContext from controller to services, repositories because I dont use _context in controler now. Now in constructor I injected services. In tests still is :

_controller = new CategoryController(_context);

but It should be: 
_controller = new CategoryController(AddCategoryService addCategoryService, GetCategoriesService getCategoriesService);

Can I change tests for my implementation ?

**Comment by SieBRUM** [comment]
Feel free to change tests accordingly to changes in the 'real' controllers etc. :) Tests are required to run succesfully to merge changes into dev (and tests are not allowed to be removed, with the exception when the corresponding 'real' methods are removed)

Quick heads-up; This organisation (and its repositories) are used for educational purposes (and are used as 'real life' projects) for the [Fontys University of Applied Sciences](https://fontys.edu/) and are meant for students within the IT bachelor study. If you are not currently part of this study, changes might not be merged into dev. 

Maybe @patrickdb can elaborate further on this topic / help you out :) 


EDIT: Ofcourse; feel free to open a PR to dev with your changes! Even when they are not merged into dev, the example of how a professional makes changes and creates a PR is extremely educational for relatively new students!

**Comment by KrzysztofBorowiecki** [comment]
I understand . I am not part of this study. So I leave this task to someone who is part of it. Thank you for your response.

**Comment by SieBRUM** [comment]
Thanks for your interest though! And if you've made any changes; please feel free to open a Pull Request as 'DRAFT' so students can use your changes as a reference :)

**Comment by patrickdb** [comment]
Hi Krzysztof,

I am one of the teachers that follow and guide this project. The goal I have is to pilot some projects in the real world and offer a development project that is as real as possible for our students to contribute to. As SieBrum suggested a draft pull request with your improvement suggestions, might be a cool case for students to learn from or decide if it is suitable to be taken in.

Btw, Your suggested improvement raised a question. I understand you want to add a new layer by introducing the service classes. Why did you split this class in an get and add class separately instead of a CategoryService with 2 different methods?

**Comment by KrzysztofBorowiecki** [comment]
Of course I will add my changes as draft pull request.

Answering to your question, I created 2 separate class because first rule of SOLID not allow me to created 1 common class.

Add and Get method have a diffrent funcionality and diffrent responsibility. 

Add is response to adding, Get to geting categories. So according to first roule of SOLID every  class should has one responsibility. So I created 2 class. One class responsibility for adding and second responsibility for geting.

On this issue I use also repository pattern for bigger controllers. but for smaller I created services.

Pleas answer me I'ts a good approach for this Issue ? What do you thinking about that.

**Comment by patrickdb** [comment]
Definitely, good thinking to take up "the single responsibility" from SOLID.

However, I think you took the single responsibility on a too fine level here. Although, there is also something called the single responsibility principle (SRP) introduced by Robert C. Martin. Which states that on every level (class/method/function/component) you should try to strive for single responsibility, or high cohesion within that specific class/method/function/component/...

SOLID aims on properties on class level. Single Responsibility, asks the question if the methods present in the class, all manipulate/handle on domain object/data with one specific goal. The "S" is about the cohesion of a class. Wikipedia [refers ](https://web.archive.org/web/20150202200348/http://www.objectmentor.com/resources/articles/srp.pdf )to an article on "single responsibility" explaining this.

In Object-Oriented design, a class is an abstraction where the domain data is hidden and methods can be used from the outside to manipulate this hidden data.  The methods publicly visible can be seen as a logical set of operations/methods on this data. If for example, you have the Order class with methods to change properties like items, status. But, also an operation\method to perform a payment. Then it is definitely not SOLID. These methods serve 2 different goals: Managing the order and Administering a payment.

The same holds if you have a controller class that handles incoming events, performs business logic, and has internal processing of the data to databases (3 responsibilities). The only responsibility it should have is to handle an outside event, and dispatch it to the right internal objects (services, validation classes, repositories, ...).

While the Add and Get methods on the CategoryService both have the function to do something with the category data, it is fine to keep them together in one class. Still, there is only one responsible for the CategoryService class, and that is managing the Category data (probably some standard CRUD operations). What you might question is, what is the actual responsibility of your service?? Some validation checks on the data, before it is handed over to a repository?

On your question about services and repositories. Look at the purpose of these patterns and decide.

Repositories: Abstraction of data persistence. A class that is a repository, probably needs to store or retrieve data... 

Service: I think the definition of a service is less clear in practice. Certain frameworks (like Spring) use it standard in their vocabulary). Others use the same terminology, but have different meanings. My interpretation of a service is some class that offers a specific piece of functionality to other classes, e.g. _authenticationService_ or _postalcodeService_. But it does not necessarily persist data.

**Comment by Noodleyy** [comment]
Refactored.
